POST http://localhost:3001/login
Content-Type: application/json

{
    "username":"shafi",
    "password":"shafi@22"
}

###
GET http://localhost:3001/jobby/jobs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNoYWZpIiwiaWF0IjoxNzAyOTY4NTY5fQ.215TrY-v9CF4XFN9LbRmfwFh1bRiQ4NlBIAt8gERTwc
