POST http://localhost:3001/login
Content-Type: application/json

{
    "username":"shafi",
    "password":"shafi@22"
}

###
GET http://localhost:3001/jobby/jobs?employment_type=FULLTIME,PARTTIME&minimum_package=10&search=data
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNpdmEiLCJpYXQiOjE3MDI5Njg0MTB9.dlBZAq913jxBxk59E8HAkJnRbKejlG0tvAwPhTeVeEM